..\..\mkcom
pause
edit mkcom.out mkcom.n   c:\wrdapp\lib3.2\msg\hspf12\perlndts.seq
edit mkcom.spe mkcom.spa c:\wrdapp\lib3.2\msg\hspf12\specact.seq
edit mkcom.sec c:\wrdapp\lib3.2\src\hspf12\hper.for
edit mkcom.sec c:\wrdapp\lib3.2\src\hspf12\hperwat.for
fc CPLPG.INC c:\wrdapp\lib3.2\src\hspf12\CPLPG.INC
pause
edit CPLPG.INC c:\wrdapp\lib3.2\src\hspf12\CPLPG.INC
fc CPLAT.INC c:\wrdapp\lib3.2\src\hspf12\CPLAT.INC
pause
edit CPLAT.INC c:\wrdapp\lib3.2\src\hspf12\CPLAT.INC
fc CPLSN.INC c:\wrdapp\lib3.2\src\hspf12\CPLSN.INC
pause
edit CPLSN.INC c:\wrdapp\lib3.2\src\hspf12\CPLSN.INC
fc CPLPW.INC c:\wrdapp\lib3.2\src\hspf12\CPLPW.INC
pause
edit CPLPW.INC c:\wrdapp\lib3.2\src\hspf12\CPLPW.INC
fc CPLSE.INC c:\wrdapp\lib3.2\src\hspf12\CPLSE.INC
pause
edit CPLSE.INC c:\wrdapp\lib3.2\src\hspf12\CPLSE.INC
fc CPLST.INC c:\wrdapp\lib3.2\src\hspf12\CPLST.INC
pause
edit CPLST.INC c:\wrdapp\lib3.2\src\hspf12\CPLST.INC
fc CPLPS.INC c:\wrdapp\lib3.2\src\hspf12\CPLPS.INC
pause
edit CPLPS.INC c:\wrdapp\lib3.2\src\hspf12\CPLPS.INC
fc CPLPQ.INC c:\wrdapp\lib3.2\src\hspf12\CPLPQ.INC
pause
edit CPLPQ.INC c:\wrdapp\lib3.2\src\hspf12\CPLPQ.INC
fc CPLMS.INC c:\wrdapp\lib3.2\src\hspf12\CPLMS.INC
pause
edit CPLMS.INC c:\wrdapp\lib3.2\src\hspf12\CPLMS.INC
fc CPLPE.INC c:\wrdapp\lib3.2\src\hspf12\CPLPE.INC
pause
edit CPLPE.INC c:\wrdapp\lib3.2\src\hspf12\CPLPE.INC
fc CPLNI.INC c:\wrdapp\lib3.2\src\hspf12\CPLNI.INC
pause
edit CPLNI.INC c:\wrdapp\lib3.2\src\hspf12\CPLNI.INC
fc CPLPH.INC c:\wrdapp\lib3.2\src\hspf12\CPLPH.INC
pause
edit CPLPH.INC c:\wrdapp\lib3.2\src\hspf12\CPLPH.INC
fc CPLTR.INC c:\wrdapp\lib3.2\src\hspf12\CPLTR.INC
pause
edit CPLTR.INC c:\wrdapp\lib3.2\src\hspf12\CPLTR.INC
