      SUBROUTINE FINDSC(AWESI,ASC,ADC)
C     RUNOFF BLOCK
C     CALLED BY AREAL NEAR LINE 51
C=======================================================================
C
C     PART OF UF SNOW MELT ROUTINES, OCT. 4, 1977, BY W. HUBER
C     THIS ROUTINE PERFORMS LINEAR INTERPOLATION ON AREAL DEPLETION
C        CURVES .  CALLED BY SUBROUTINE AREAL.
C
      DIMENSION ADC(10)
C
C     ARRAY ADC IS AREAL DEPLETION CURVE FOR PERVIOUS OR IMPERV. AREAS.
C     AWESI IS SNOW WATER EQUIV DIVIDED BY MAX FOR THAT AREA.
C     (AWESI IS ORDINATE, ADC IS ABSCISSA.)
C
      IF(AWESI.GT.0.0) GO TO 10
      ASC=0.0
      RETURN
   10 IF(AWESI.GE.0.9999) GO TO 20
      IW=AWESI*10.+1.00001
C
C     UPPER VALUE FOR BOTH ORDINATE AND ABSCISSA MUST BE 1.0.
C
      IF(IW.GE.10) ADCUP=1.0
      IF(IW.LE.9) ADCUP=ADC(IW+1)
C
C     LINEAR INTERPOLATION ON AREAL DEPLETION CURVE.
C
      ASC=ADC(IW)+(ADCUP-ADC(IW))/0.1*(AWESI-0.1*FLOAT(IW-1))
      RETURN
   20 ASC=1.0
      RETURN
      END
