      SUBROUTINE SSSTATUS(IOPTION)
C	EXTRAN BLOCK
C	CALLED BY INTERCON (64) and TRANSX (905 and 909)
CIM  SUBROUTINE WRITTEN BY C. MOORE TO PRINT MESSAGES RELATED TO STATUS
CIM  OF STEADY STATE VS NON-STEADY CALCULATIONS
CIM   1/98
CIM
      INCLUDE 'TAPES.INC'
      INCLUDE 'INTCON.INC'
      INCLUDE 'CONTR.INC'
      INCLUDE 'STIMER.INC'
      SELECT CASE (IOPTION)
      CASE (1)
CIM  HERE WHEN PROGRAM GOES FROM STEADY TO NON STEADY
      WRITE(N6,9100) MONTH,NDAY,NYEAR,JHR,MINUTE,JSEC,
     aJULDAY+TIMDAY/24.0/60.0/60.0,ICYC,TIME/3600.0
      IF (CONSTINFLOW) THEN
      WRITE(N6,9300)
      ELSE
      WRITE(N6,9310)
      ENDIF
      IF (SMALLOUTFLOW) THEN
      WRITE(N6,9320)
      ELSE
      WRITE(N6,9330)
      ENDIF
      IF (EQUALINOUT) THEN
      WRITE(N6,9340)
      ELSE
      WRITE(N6,9350)
      ENDIF
      CASE (2)
CIM  HERE TO WRITE PROGRAM STATUS
      IF (NOROUT.EQ.0) THEN
      WRITE(N6,9200)
      IF (CONSTINFLOW) THEN
      WRITE(N6,9300)
      ELSE
      WRITE(N6,9310)
      ENDIF
      IF (SMALLOUTFLOW) THEN
      WRITE(N6,9320)
      ELSE
      WRITE(N6,9330)
      ENDIF
      IF (EQUALINOUT) THEN
      WRITE(N6,9340)
      ELSE
      WRITE(N6,9350)
      ENDIF
      ELSE
      WRITE(N6,9210)
      ENDIF
      CASE (3)
CIM  HERE TO SIMPLY WRITE THE STATUS OF PROGRAM VARIABLES
      IF (CONSTINFLOW) THEN
      WRITE(N6,9300)
      ELSE
      WRITE(N6,9310)
      ENDIF
      IF (SMALLOUTFLOW) THEN
      WRITE(N6,9320)
      ELSE
      WRITE(N6,9330)
      ENDIF
      IF (EQUALINOUT) THEN
      WRITE(N6,9340)
      ELSE
      WRITE(N6,9350)
      ENDIF
      CASE (4)
cim here when program goes from non-steady to steady
      WRITE(N6,9400) MONTH,NDAY,NYEAR,JHR,MINUTE,JSEC,
     AJULDAY+TIMDAY/24.0/60.0/60.0,ICYC,TIME/3600.0
      IF (.NOT. CONSTINFLOWO) WRITE(N6,9410)
      IF (.NOT. SMALLOUTFLOWO) WRITE(N6,9420)
      IF (.NOT. EQUALINOUTO) WRITE(N6,9430)
      CONSTINFLOWO = CONSTINFLOW
      SMALLOUTFLOWO = SMALLOUTFLOW
      EQUALINOUTO = EQUALINOUT
      END SELECT
      RETURN
 9100 FORMAT(//,10X,'<><><> PROGRAM HAS GONE FROM STEADY TO NON-STEADY',
     a' STATE MODE <><><>',/,
     b18X,'DATE AND TIME OF DAY = ',I2,'/',I2,'/',I4,I3,':',I2,':',I2,
     c9X,'JULIAN DATE          = ',F14.3,/,
     d18X,'SIMULATION TIME STEP = ',I19,
     e9X,'SIMULATION HOURS     = ',F14.3)
 9210 FORMAT(//,10X,'<><><> PROGRAM IS IN STEADY STATE MODE')
 9200 FORMAT(10X,'<><><> PROGRAM IS NOT IN STEADY STATE MODE')
 9300 FORMAT(15X,'INFLOWS ARE STEADY')
 9310 FORMAT(15X,'INFLOWS ARE NOT STEADY')
 9320 FORMAT(15X,'OUTFLOWS ARE LESS THAN SPECIFIED MINIMUM')
 9330 FORMAT(15X,'OUTFLOWS ARE NOT LESS THAN SPECIFIED MINIMIM')
 9340 FORMAT(15X,'INFLOWS AND OUTFLOWS ARE EQUAL')
 9350 FORMAT(15X,'INFLOWS AND OUTFLOWS ARE NOT EQUAL')
 9400 FORMAT(//,10X'<><><> PROGRAM HAS SWITCHED FROM NON-STEADY TO ',
     a'STEADY STATE MODE.',/,
     b18X,'DATE AND TIME OF DAY = ',I2,'/',I2,'/',I4,I3,':',I2,':',I2,
     c9X,'JULIAN DATE          = ',F14.3,/,
     d18X,'SIMULATION TIME STEP = ',I19,
     e9X,'SIMULATION HOURS     = ',F14.3,/,
     f10X,'THE FOLLOWING DESCRIBES THE ',
     g'CONDITIONS THAT CHANGED TO ALLOW STEADY STATE CALCULATIONS.')
 9410 FORMAT(15X,' INFLOW BECAME CONSTANT')
 9420 FORMAT(15X,' OUTFLOW BECAME LESS THAN MINIMUM FLOW')
 9430 FORMAT(15X,' OUTFLOW EQUALS INFLOW')
      END
