#
# MKMF template makefile for protected mode executables.
#
FC        = f77l3
LINKER    = 386link
PROGRAM   = mkcom.exe
FFLAGS    = /S
LDFLAGS   = -stub runb,vmmb -SYMBOLS -PACK
LIBS      = c:\wrdapp\lib3.2\aide.lib  c:\wrdapp\lib3.2\util.lib

MAKEFILE  = Makefile
OBJS      = mkcom.obj

SRCLOC = \mkcom

$(PROGRAM):     $(OBJS) $(LIBS)
          $(LINKER) $(OBJS) -EXE $@ -NOMAP -LIB $(LIBS) $(LDFLAGS) -PACK -stub runb,vmmb
