
c     begin include file cbgout.inc

c     + + + COMMON BLOCK DESCRIPTION + + +
c     + + + INSERT DESCRIPTION HERE  + + +

      common /bgout/     ralmin(80),ralmax(80),intmin(8),intmax(8)

c     + + + VARIABLE DECLARATIONS + + +

      real              ralmin,ralmax
      integer           intmin,intmax

c     + + + VARIABLE DEFINITIONS + + +

c     ralmin(80):  minimum value for real variables in bigout
c     ralmax(80):  maximum value for real variables in bigout
c     intmin(8) :  minimum value for integer variables in bigout
c     intmax(8) :  maximum value for integer variables in bigout
c
c     end include file cbgout.inc

