
c     begin include file cchcas.inc

c     + + + COMMON BLOCK DESCRIPTION + + +
c     + + + INSERT DESCRIPTION HERE  + + +

      common /chcas/ qlat,ql,wfu,wfl,flagc,chz,chn,crsh,dx,
     1    effshl,depsid,tb,sfl,cc1,xdemax

c     + + + VARIABLE DECLARATIONS + + +

      real      qlat,ql,wfu,wfl,chz,chn,crsh,dx,effshl,depsid,tb,
     1          sfl,cc1,xdemax
      integer   flagc

c     + + + VARIABLE DEFINITIONS + + +

c     qlat   :
c     ql     :
c     wfu    :
c     wfl    :
c     flagc  :
c     chz    :
c     chn    :
c     crsh   :
c     dx     :
c     effshl :
c     depsid :
c     tb     :
c     sfl    :
c     cc1    :
c     xdemax :

c     end include file cchcas.inc


