
c     begin include file cchcon.inc

c     + + + COMMON BLOCK DESCRIPTION + + +
c     + + + INSERT DESCRIPTION HERE  + + +

      common /chcon/ agrav,msdh2o,wtdh2o,wtdsoi,knvis,yalcon,beta,nbarch

c     + + + VARIABLE DECLARATIONS + + +

      real           agrav,msdh2o,wtdh2o,wtdsoi,knvis,yalcon,beta,nbarch

c     + + + VARIABLE DEFINITIONS + + +

c     agrav  :
c     msdh2o :
c     wtdh2o :
c     wtdsoi :
c     knvis  :
c     yalcon :
c     beta   :
c     nbarch :

c     end include file cchcon.inc

