
c     begin include file cchflo.inc

c     + + + COMMON BLOCK DESCRIPTION + + +
c     + + + INSERT DESCRIPTION HERE  + + +

      common /chflo/ cflags,qb,qe,ycr,ynor,ye,sfe

c     + + + VARIABLE DECLARATIONS + + +

      real           qb,qe,ycr,ynor,ye,sfe
      integer        cflags

c     + + + VARIABLE DEFINITIONS + + +

c     cflags :
c     qb     :
c     qe     :
c     ycr    :
c     ynor   :
c     ye     :
c     sfe    :

c     end include file cchflo.inc

