
c     begin include file ccliyr.inc

c     + + + COMMON BLOCK DESCRIPTION + + +
c     + + + INSERT DESCRIPTION HERE  + + +

      common /cliyr/    ibyear,numyr,nyear

c     + + + VARIABLE DECLARATIONS + + +

      integer           ibyear,numyr,nyear

c     + + + VARIABLE DEFINITIONS + + +

c     ibyear : beginning year of simulation
c     numyr  : maximum number of years in climate file
c     nyear  : number of years of simulation

c     end include file ccliyr.inc

