
c     begin include file ccontcv.inc

c     + + + COMMON BLOCK DESCRIPTION + + +
c     + + + INSERT DESCRIPTION HERE  + + +

      common /contcv/   tilseq(mxcrop,mxplan),tilflg

c     + + + VARIABLE DECLARATIONS + + +

      integer           tilseq,tilflg

c     + + + VARIABLE DEFINITIONS + + +

c     tilseq(mxcrop,mxplan) : tillage sequence indicator for current
c                             crop on the current ofe
c     tilflg                : flag to indicate if tillage has been called

c     end include file ccontcv.inc

