
c     begin include file cconsta.inc

c     + + + COMMON BLOCK DESCRIPTION + + +
c     + + + INSERT DESCRIPTION HERE  + + +

      common /consta/   accgav,wtdens,kinvis,msdens

c     + + + VARIABLE DECLARATIONS + + +

      real              accgav,wtdens,kinvis,msdens

c     + + + VARIABLE DEFINITIONS + + +

c     accgav : acceleration of gravity (m/s^2)
c     wtdens : specific weight of water (kg/m^2/s^2)
c     kinvis : kinematic viscosity of water (m^2/s)
c     msdens : specific mass of water (kg/m^3)

c     end include file cconsta.inc

