
c     begin include file ccrpvr5a.inc

c     + + + COMMON BLOCK DESCRIPTION + + +
c     + + + INSERT DESCRIPTION HERE  + + +

      common /crpvr5a/   pltsp(ntype),diam(ntype)

c     + + + VARIABLE DECLARATIONS + + +

      real               pltsp, diam

c     + + + VARIABLE DEFINITIONS + + +

c     pltsp(ntype) : plant spacing (m)
c     diam(ntype)  : plant stem diameter at maturity (m)

c     end include file ccrpvr5a.inc

