
c     begin include file cdata3.inc

c     + + + COMMON BLOCK DESCRIPTION + + +
c     + + + INSERT DESCRIPTION HERE  + + +

      common /data3/    dt,nr,nf,nm,nqt

c     + + + VARIABLE DECLARATIONS + + +

      real              dt
      integer           nr,nf,nm,nqt

c     + + + VARIABLE DEFINITIONS + + +

c     dt  : infiltration time step (s)
c     nr  : number of rainfall intervals
c     nf  : number of infiltration intervals
c     nm  : maximum rainfall excess index
c     nqt : number of runoff intervals

c     end include file cdata3.inc

