
c     begin include file cdata1.inc

c     + + + COMMON BLOCK DESCRIPTION + + +
c     + + + INSERT DESCRIPTION HERE  + + +

      common /data1/ tr(mxtime),r(mxtime), rr(mxtime)

c     + + + VARIABLE DECLARATIONS + + +

      real           tr,r,rr

c     + + + VARIABLE DEFINITIONS + + +

c     tr(mxtime): array with time increments for rainfall
c     r(mxtime) : rainfall rate (m/s)
c     rr(mxtime): rainfall depths (m)

c     end include file cdata1.inc

