
c     begin include file cdetcom.inc

c     + + + COMMON BLOCK DESCRIPTION + + +
c     + + + INSERT DESCRIPTION HERE  + + +

      common /detcom/ xx,eatax,taucx,shr,dcap

c     + + + VARIABLE DECLARATIONS + + +

      real            xx,eatax,taucx,shr,dcap

c     + + + VARIABLE DEFINITIONS + + +

c     xx     : previous value of x.
c     eatax  : previous value of eata.
c     taucx  : previous value of tauc.
c     shr    :
c     dcap   : detachment capacity at a point

c     end include file cdetcom.inc

