
c     begin include file cdiss12.inc

c     + + + COMMON BLOCK DESCRIPTION + + +
c     + + + INSERT DESCRIPTION HERE  + + +

      common /diss12/   intsty(100),timem(100)

c     + + + VARIABLE DECLARATIONS + + +

      real              intsty,timem

c     + + + VARIABLE DEFINITIONS + + +

c     intsty(100) : rainfall intensity (m/s)
c     timem(100)  : elapsed time (s)

c     end include file cdiss12.inc

