
c     begin include file cdiss2.inc

c     + + + COMMON BLOCK DESCRIPTION + + +
c     + + + INSERT DESCRIPTION HERE  + + +

      common /diss2/  intdl(20),timedl(20)

c     + + + VARIABLE DECLARATIONS + + +

      real            intdl,timedl

c     + + + VARIABLE DEFINITIONS + + +

c     intdl(20)  : dimensionless rainfall intensity
c     timedl(20) : dimensionless elapsed time

c     end include file cdiss2.inc

