
c     begin include file cdist1.inc

c     + + + COMMON BLOCK DESCRIPTION + + +
c     + + + INSERT DESCRIPTION HERE  + + +

c     NOTE : DIST1 is used in the child routines of SR ROUTE.

      common /dist1/    xinput(101,mxplan)

c     + + + VARIABLE DECLARATIONS + + +

      real              xinput

c     + + + VARIABLE DEFINITIONS + + +

c     xinput(101,mxplan) : unitless distances (points) down the slope

c     end include file cdist1.inc

