
c     begin include file cends3.inc

c     + + + COMMON BLOCK DESCRIPTION + + +
c     + + + INSERT DESCRIPTION HERE  + + +

c     NOTE : ENDS3 is used in SR ROUTE.

      common /ends3/    strldn

c     + + + VARIABLE DECLARATIONS + + +

      real              strldn

c     + + + VARIABLE DEFINITIONS + + +

c     strldn : nondimensional sediment load at the top (inlet) of
c              the current OFE.

c     end include file cends3.inc

