
c     begin include file cfall.inc

c     + + + COMMON BLOCK DESCRIPTION + + +
c     + + + INSERT DESCRIPTION HERE  + + +

      common /fall/     cdre(9),cdre2(9),cddre(9)

c     + + + VARIABLE DECLARATIONS + + +

      real              cdre,cdre2,cddre

c     + + + VARIABLE DEFINITIONS + + +

c     cdre(9)  : coefficient for particle size calculations
c     cdre2(9) : coefficient for particle size calculations
c     cddre(9) : coefficient for particle size calculations

c     end include file cfall.inc

