
c     begin include file cfripas.inc

c
      common /fripas/  frrrok, inrfto, rillar, frirok, inrfro,
     1                 frrraf, frires, frrbas

c     + + + VARIABLE DECLARATIONS + + +

      real             frrrok, inrfto, rillar, frirok, inrfro,
     1                 frrraf, frires, frrbas

c     + + + VARIABLE DEFINITIONS + + +

c     frrrok()  : rill friction due to rock and gravel
c     inrfto()  : total interrill friction
c     rillar()  : rill area
c     frirok()  : interrill friction due to rock and gravel
c     inrfro()  : interrill friction due to random roughness
c     frrraf()  : rill friction due to random roughness
c     frires()  : interrill friction due to litter
c     frrbas()  : rill friction due to basal vegetation

c     end include file cfripas.inc
