
c     begin include file cgully.inc

c     + + + COMMON BLOCK DESCRIPTION + + +
c     + + + INSERT DESCRIPTION HERE  + + +

      common /gully/   depa(mxplan,mxcseg),depb(mxplan,mxcseg),
     1                 wida(mxplan,mxcseg),widb(mxplan,mxcseg),
     1                 wera(mxplan,mxcseg),werb(mxplan,mxcseg)

c     + + + VARIABLE DECLARATIONS + + +

      real             depa,depb,wida,widb,wera,werb

c     + + + VARIABLE DEFINITIONS + + +

c     depa(mxplan,mxcseg) :
c     depb(mxplan,mxcseg) :
c     wida(mxplan,mxcseg) :
c     widb(mxplan,mxcseg) :
c     wera(mxplan,mxcseg) :
c     werb(mxplan,mxcseg) :

c     end include file cgully.inc

