
c     begin include file cupdate.inc

c     + + + COMMON BLOCK DESCRIPTION + + +
c     + + + INSERT DESCRIPTION HERE  + + +

      common /imdate/ ddate,dyear

c     + + + VARIABLE DECLARATIONS + + +

      integer  ddate,dyear

c     + + + VARIABLE DEFINITIONS + + +

c     dyear                 : year of simulation
c     ddate                : date of year in Julian date
c     end include file cupdate.inc

