
c     begin include file ciplot.inc

c     + + + COMMON BLOCK DESCRIPTION + + +
c     + + + INSERT DESCRIPTION HERE  + + +

      common /iplot/     ievt, ifofe, isum

c     + + + VARIABLE DECLARATIONS + + +

      integer            ievt, ifofe, isum

c     + + + VARIABLE DEFINITIONS + + +

c     ievt :  flag to indicate event by event summary outputs
c               are to be written.  (0 - no; 1 - yes)
c     ifofe :  flag to indicate OFE summary outputs (0 - no; 1 - yes)
c     isum :  flag to indicate final summary table generation
c               (0 - no; 1 - yes)

c     end include file ciplot.inc

