
c     begin include file cirflg.inc

c     + + + COMMON BLOCK DESCRIPTION + + +
c     + + + INSERT DESCRIPTION HERE  + + +

      common /irflg/ irdfg 

c     + + + VARIABLE DECLARATIONS + + +

      integer      irdfg 

c     + + + VARIABLE DEFINITIONS + + +

c     irdfg  : flag for depletion level scheduling irrigation scheme
c                0 = No depletion-level irrigation applied 
c                1 = depletion level scheduling irrigation 
c
c     end include file cirflg.inc

