
c     begin include file cnew1.inc

c     + + + COMMON BLOCK DESCRIPTION + + +
c     + + + INSERT DESCRIPTION HERE  + + +

      common /new1/     critvm(ntype)

c     + + + VARIABLE DECLARATIONS + + +

      real              critvm

c     + + + VARIABLE DEFINITIONS + + +

c     critvm(ntype) : critical live biomass value below which
c                     grazing is not allowed (kg/m^2)

c     end include file cnew1.inc

