
c     begin include file cobclim.inc

c     + + + COMMON BLOCK DESCRIPTION + + +
c     + + + INSERT DESCRIPTION HERE  + + +

      common /obclim/   obmaxt(12),obmint(12),radave(12),obrain(12)

c     + + + VARIABLE DECLARATIONS + + +

      real              obmaxt,obmint,radave,obrain

c     + + + VARIABLE DEFINITIONS + + +

c     obmaxt(12) : observed average monthly maximum temperature (degrees C)
c     obmint(12) : observed average monthly minimum temperature (degrees C)
c     radave(12) : observed average monthly radiation (Langleys/day)
c     obrain(12) : observed average monthly rainfall (mm)

c     end include file cobclim.inc

