
c     begin include file coutchn.inc

c     + + + COMMON BLOCK DESCRIPTION + + +
c     + + + INSERT DESCRIPTION HERE  + + +

      common /outchn/   tgst(mxpart,mxelem),tgsm(mxpart,mxelem),
     1                  tgsy(mxpart,mxelem),nrunm,nruny,nrunt,
     1                  trunm(mxelem),truny(mxelem),trunt(mxelem),
     1                  nsedm(mxcseg),csedm(mxcseg),nsedy(mxcseg),
     1                  csedy(mxcseg),nsedt(mxcseg),csedt(mxcseg),
     1                  cdetm(mxelem),cdety(mxelem),cdett(mxelem),
     1                  cdepm(mxelem),cdepy(mxelem),cdept(mxelem),
     1                  tgsd(mxpart,mxelem),tronvy(mxelem),
     1                  sbrfty(mxelem),sbrvty(mxelem),
     1                  sbrvtt(mxelem),tronvt(mxelem),
     1                  sbrftm(mxelem)


c     + + + VARIABLE DECLARATIONS + + +

      real              tgst,tgsm,tgsy,trunm,truny,trunt,nsedm,
     1                  csedm,nsedy,csedy,nsedt,csedt,cdetm,
     1                  cdety,cdett,cdepm,cdepy,cdept,tgsd,
     1                  sbrvty,sbrfty,tronvy,tronvt,sbrvtt,
     1                  sbrftm
      integer           nrunm,nruny,nrunt

c     + + + VARIABLE DEFINITIONS + + +

c     tgst(mxpart,mxelem) :
c     tgsm(mxpart,mxelem) :
c     tgsy(mxpart,mxelem) :
c     nrunm               :
c     nruny               :
c     nrunt               :
c     trunm(mxelem)       :
c     truny(mxelem)       :
c     trunt(mxelem)       :
c     nsedm(mxcseg)       :
c     csedm(mxcseg)       :
c     nsedy(mxcseg)       :
c     csedy(mxcseg)       :
c     nsedt(mxcseg)       :
c     csedt(mxcseg)       :
c     cdetm(mxelem)       :
c     cdety(mxelem)       :
c     cdett(mxelem)       :
c     cdepm(mxelem)       :
c     cdepy(mxelem)       :
c     cdept(mxelem)       :

c     end include file coutchn.inc

