
c     begin include file coutfg.inc

c     + + + COMMON BLOCK DESCRIPTION + + +
c     + + + INSERT DESCRIPTION HERE  + + +

      common /outflags/  lunp,luns,lunw

c     + + + VARIABLE DECLARATIONS + + +

      integer            lunp,luns,lunw

c     + + + VARIABLE DEFINITIONS + + +

c     lunp,luns,lunw - flag indicating that user wants
c                      plant, soil, or water output respectively
c                      (1 - yes ;  0 - no )

c     end include file coutfg.inc

