
c     begin include file cparva1.inc

c     + + + COMMON BLOCK DESCRIPTION + + +
c     + + + INSERT DESCRIPTION HERE  + + +

c     NOTE : PARVA1 is used in SR ROUTE.

      common /parva1/   eata,tauc,theta,phi

c     + + + VARIABLE DECLARATIONS + + +

      real              eata,tauc,theta,phi

c     + + + VARIABLE DEFINITIONS + + +

c     eata  : unitless parameter for rill erosion
c     tauc  : unitless parameter for rill critical shear stress
c     theta : unitless parameter for interrill erosion
c     phi   : unitless parameter for deposition

c     end include file cparva1.inc

