
c     begin include file cparva2.inc

c     + + + COMMON BLOCK DESCRIPTION + + +
c     + + + INSERT DESCRIPTION HERE  + + +

c     NOTE : PARVA2 is never used in SR ROUTE.

      common /parva2/   shcrit(mxplan)

c     + + + VARIABLE DECLARATIONS + + +

      real              shcrit

c     + + + VARIABLE DEFINITIONS + + +

c     shcrit(mxplan) : rill detachment threshold parameter,
c                      or critical shear stress (kg/m/s^2)

c     end include file cparva2.inc

