
c     begin include file cprams1.inc

c     + + + COMMON BLOCK DESCRIPTION + + +
c     + + + INSERT DESCRIPTION HERE  + + +

      common /prams1/   m,tstar

c     + + + VARIABLE DECLARATIONS + + +

      real              m,tstar

c     + + + VARIABLE DEFINITIONS + + +

c     m      : Chezy depth-discharge exponent
c     tstar  : time when rainfall excess stops (s)

c     end include file cprams1.inc

