
c     begin include file cstmflg.inc

c     + + + COMMON BLOCK DESCRIPTION + + +
c     + + + INSERT DESCRIPTION HERE  + + +

      common /stmflg/   norain(mxplan),nmon,jyear

c     + + + VARIABLE DECLARATIONS + + +

      integer           norain,nmon,jyear

c     + + + VARIABLE DEFINITIONS + + +

c     norain : flag for no rain
c     nmon   : flag for month
c     jyear  : flag for simulation year

c     end include file cstmflg.inc

