
c     begin include file cstmgt.inc

c     + + + COMMON BLOCK DESCRIPTION + + +
c     + + + INSERT DESCRIPTION HERE  + + +

      common /stmgt/    nrec,tmp(6),tmpx(6),idtot

c     + + + VARIABLE DECLARATIONS + + +

      real              tmp,tmpx
      integer           nrec,idtot

c     + + + VARIABLE DEFINITIONS + + +

c     nrec    :
c     tmp(6)  :
c     tmpx(6) :
c     idtot   :

c     end include file cstmgt.inc

