
c     begin include file ctcurv.inc

c     + + + COMMON BLOCK DESCRIPTION + + +
c     + + + INSERT DESCRIPTION HERE  + + +

      common /tcurv/YavgT,YampT,YpshfT,obavgT(12)

c     + + + VARIABLE DECLARATIONS + + +

      real           YavgT,YampT,YpshfT,obavgT

c     + + + VARIABLE DEFINITIONS + + +

c     YavgT : Yearly average air temperature (degrees C)  
c     YampT : Monthly average air temperature change amplitude (degrees C)
c     YpshfT: Phase shift of the temperature curve (day) 
c     obavgT: Monthly average air temperature(degrees C)  

c     end include file ctcurv.inc

