
c     begin include file cver.inc

c     + + + COMMON BLOCK DESCRIPTION + + +
c     + + + INSERT DESCRIPTION HERE  + + +

      common /ver/ ver, veryr, vermon

c     + + + VARIABLE DECLARATIONS + + +

      real ver
      integer veryr
      character*17 vermon

c     + + + VARIABLE DEFINITIONS  + + +

c     ver   : WEPP version number
c     veryr : year version was created
c     vermon: month and day version was created

c     end include file cver.inc
