
c     begin include file pmxpln.inc

c     + + + PARAMETER DECLARATIONS + + +

      integer           mxplan
      parameter         (mxplan=75)

c     + + + PARAMETER DEFINITIONS + + +

c     May be some problems with this parameter statement, check w/dcf
c
c     mxplan : (hillslope version) maximum number of overland
c              flow elements, (i.e., strips of different soils
c              and/or crops), limited to 10 in file builder

c     mxplan : (watershed version) maximum number of unique
c              channels in watershed

c     end include file pmxpln.inc

