C -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
C
      COMMON /PFILES/ ISCT,IFUN,IMAC,IMEN,ILOG,ISCN,IHLP
      COMMON /PFILE2/ CSCTFL, CFUNFL, CMACFL, CMENFL, CLOGFL, CSCNFL,
     + CHLPFL
      COMMON /PFILE1/ LMACOP, LPATT, LKEYB
      CHARACTER*20 CSCTFL, CFUNFL, CMACFL, CMENFL, CLOGFL, CSCNFL,
     +    CHLPFL
      LOGICAL LMACOP, LPATT, LKEYB
C
C -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
