      SUBROUTINE TRUNAM(CPSUDO,CTRU,CNAMES,INAMES)
C
C     ASSOCIATED WITH ROUTINE SETNAM
C     USER SENDS TRUNAM IPSUD0 AND NAMES LIST,
C     ROUTINE SENDS BACK ITRU (TRUE NAME)
C     IF ITRU NOT FOUND SENDS BACK ITRU BLANK
C     IF IPSUDO IS TRUE NAME, SENDS ITRU (=IPSUDO)
C     FORTRAN 66 COMPATIABLE
C
      CHARACTER CNAMES*(*)
      DIMENSION CNAMES(*)
      CHARACTER CPSUDO*(*),CTRU*(*)
      DIMENSION INAMES(-4:*)
C
C
      CALL NSERCH(CPSUDO,LOCT,CNAMES,INAMES)
      IF (LOCT.GT.0) GO TO 20
C
C     DID NOT FIND A NAME, RETURN CTRU BLANK
C
      CALL CHRBLK(CTRU)
      RETURN
C
C     DID FIND A NAME, RETURN ITRU WITH TRUE NAME
C
20    CTRU = CNAMES(INAMES(LOCT))
      RETURN
      END
