      SUBROUTINE VATT (IATT)
C     SET ATT TO IATT
C     0 = NORMAL
C     1 = BOLD
C     4 = UNDERLINE
C     5 = BLINKING
C     7 = REVERSE VIDEO
      LOGICAL LANSI,LFIRST,LCRT
      INTEGER IVUNIT
      COMMON/LANSI/LANSI,LFIRST,LCRT,IVUNIT
      CHARACTER C*8
      IF(LANSI) THEN
        WRITE(C,5) CHAR(27),IATT
 5      FORMAT(A1,'[',I2.2,'m')
        CALL CHRWT(IVUNIT,C,5)
      ENDIF
      RETURN
      END
