..\..\mkcom
pause
edit mkcom.out mkcom.n   c:\wrdapp\lib3.2\msg\hspf13\rchrests.seq
edit mkcom.spe mkcom.spa c:\wrdapp\lib3.2\msg\hspf13\specact.seq
edit mkcom.sec c:\wrdapp\lib3.2\src\hspf13\hrch.for
edit mkcom.sec c:\wrdapp\lib3.2\src\hspf13\hrchgqu.for
edit mkcom.sec c:\wrdapp\lib3.2\src\hspf13\hrchrq.for
fc CRHGE.INC c:\wrdapp\lib3.2\src\hspf13\CRHGE.INC
pause
edit CRHGE.INC c:\wrdapp\lib3.2\src\hspf13\CRHGE.INC
fc CRHHD.INC c:\wrdapp\lib3.2\src\hspf13\CRHHD.INC
pause
edit CRHHD.INC c:\wrdapp\lib3.2\src\hspf13\CRHHD.INC
fc CRHAD.INC c:\wrdapp\lib3.2\src\hspf13\CRHAD.INC
pause
edit CRHAD.INC c:\wrdapp\lib3.2\src\hspf13\CRHAD.INC
fc CRHCO.INC c:\wrdapp\lib3.2\src\hspf13\CRHCO.INC
pause
edit CRHCO.INC c:\wrdapp\lib3.2\src\hspf13\CRHCO.INC
fc CRHHT.INC c:\wrdapp\lib3.2\src\hspf13\CRHHT.INC
pause
edit CRHHT.INC c:\wrdapp\lib3.2\src\hspf13\CRHHT.INC
fc CRHSE.INC c:\wrdapp\lib3.2\src\hspf13\CRHSE.INC
pause
edit CRHSE.INC c:\wrdapp\lib3.2\src\hspf13\CRHSE.INC
fc CRHGQ.INC c:\wrdapp\lib3.2\src\hspf13\CRHGQ.INC
pause
edit CRHGQ.INC c:\wrdapp\lib3.2\src\hspf13\CRHGQ.INC
fc CRHRQ.INC c:\wrdapp\lib3.2\src\hspf13\CRHRQ.INC
pause
edit CRHRQ.INC c:\wrdapp\lib3.2\src\hspf13\CRHRQ.INC
fc CRHOX.INC c:\wrdapp\lib3.2\src\hspf13\CRHOX.INC
pause
edit CRHOX.INC c:\wrdapp\lib3.2\src\hspf13\CRHOX.INC
fc CRHNU.INC c:\wrdapp\lib3.2\src\hspf13\CRHNU.INC
pause
edit CRHNU.INC c:\wrdapp\lib3.2\src\hspf13\CRHNU.INC
fc CRHPL.INC c:\wrdapp\lib3.2\src\hspf13\CRHPL.INC
pause
edit CRHPL.INC c:\wrdapp\lib3.2\src\hspf13\CRHPL.INC
fc CRHPH.INC c:\wrdapp\lib3.2\src\hspf13\CRHPH.INC
pause
edit CRHPH.INC c:\wrdapp\lib3.2\src\hspf13\CRHPH.INC
fc CRHAC.INC c:\wrdapp\lib3.2\src\hspf13\CRHAC.INC
pause
edit CRHAC.INC c:\wrdapp\lib3.2\src\hspf13\CRHAC.INC
