C     version information: VERSN = char*64
      VERSN = '@(#)  swstat - Surface-Water statistical analysis'
      VERSN = '@(#)  swstat - Version 2.0, 1994/05/01 (HASS tape 2)'
      VERSN = '@(#)  swstat - Version 2.1  1994/06/28 update'
      VERSN = '@(#)  swstat - Version 2.2  1994/11/01 update'
      VERSN = '@(#)  swstat - Version 3.0  1996/03/26 (HASS tape 3)'
      VERSN = '@(#)  swstat - Version 3.1  1996/09/25 update'
      VERSN = '@(#)  swstat - Version 3.1  1996/12/19 update'
      VERSN = '@(#)  swstat - Version 3.2  1998/04/03 update'
      VERSN = '@(#)  swstat - Version 4.0  2000/12/01 update'
      VERSN = '@(#)  swstat - Version 4.1  2002/02/25 update'
      VERSN = '@(#) Reports:  WRIR 95-4085, Flynn, Hummel, Lumb, Kittle'
      VERSN = '@(#)           WRIR 89-4080, Lumb, Kittle, & Flynn'
      VERSN = '@(#) Contact:  h2osoft@usgs.gov'
C
C     name of application, log file, and message file
      APNAM = 'SWSTAT 4.1'
      LGNAM = 'SWSTAT  '
      FNAME = '/usr/opt/wrdapp/swstat4.1/bin_data/swstms.wdm'
C
