C
C     include file PIOUNI.INC
C
      INTEGER   KUOUT
C
      PARAMETER (KUOUT=6)
C
C     KUOUT - Screen output - (1 = PRIME), (0 = PC), (6 = VAX)
C
      INTEGER    NMXFIL
C
      PARAMETER (NMXFIL=99)
C
C     NMXFIL - maximum number of files which can be open at one time
C
      INTEGER    FILBAS
C
      PARAMETER (FILBAS=30)
C
C     FILBAS - base number of logical unit to begin opening
C
