C     version information: VERSN = char*64
      VERSN = '@(#)PEAKFQ - Flood frequency analysis'
      VERSN = '@(#)PEAKFQ - Version 2, 1994/05/01 (HASS tape 2)'
      VERSN = '@(#)PEAKFQ - Version 2.1, 1994/08/30 update'
      VERSN = '@(#)PEAKFQ - Version 2.2, 1996/05/17 (HASS tape 3)'
      VERSN = '@(#)PEAKFQ - Version 2.3, update 1997/01/07'
      VERSN = '@(#)PEAKFQ - Version 2.4, update 1998/04/03'
      VERSN = '@(#)PEAKFQ - Version 4.0, update 2000/12/01'
      VERSN = '@(#)PEAKFQ - Version 4.1, update 2002/02/25'
      VERSN = '@(#)PEAKFQ - Version 5 Beta 1, update August 2004'
      VERSN = '@(#) Reports:  Draft, included in distribution'
      VERSN = '@(#)           Bulletin 17B'
      VERSN = '@(#)           WRIR 89-4080, Lumb, Kittle, & Flynn'
      VERSN = '@(#) Contact:  h2osoft@usgs.gov'
C
C     name of application, message file, and log file
      APNAME= 'PEAKFQ 5 Beta 1'
      LGNAME= 'PEAKFQ  '
      FNAME = 'pkfqms.wdm'
C
