C     + + + DEFINITIONS + + +
C
C     AIKNT  - number of integer attributes
C     ARKNT  - number of real attributes
C     ACKNT  - number of character attributes
C     ACLONG - Total length of all character attributes combined
C
C     AINDX  - Index number of each of the integer attributes
C     ARNDX  - Index number of each of the real attributes
C     ACNDX  - Index number of each of the character attributes
C     ACLEN  - Length of each of the character attributes being added
C     AIVAL  - Value of each of the integer attributes
C     ARVAL  - Value of each of the real attributes
C
C     AVER   - version of attributes
C              1 - attributes for time series
C              2 - attributes for basin characteristics
C     AIMX   - number of actual integer attributes, depends on AVER
C     ARMX   - number of actual real attributes, depends on AVER
C     ACMX   - number of actual character attributes, depends on AVER
C
C     AINAME - Names of each of the integer attributes
C     ARNAME - Names of each of the real attributes
C     ACNAME - Names of each of the character attributes
C     ACVAL  - Value of each or the character attributes
