grep sydatm *.for > serch.out
grep date   *.for >> serch.out
grep time   *.for >> serch.out
grep secnds *.for >> serch.out
grep timdat *.for >> serch.out
grep year   *.for >> serch.out
grep start  *.for >> serch.out
grep begin  *.for >> serch.out
grep strt   *.for >> serch.out
grep dend   *.for >> serch.out
grep dbgn   *.for >> serch.out
grep 1999   *.for >> serch.out
grep 2000   *.for >> serch.out
grep 1900   *.for >> serch.out
grep 2001   *.for >> serch.out
grep 2010   *.for >> serch.out
grep 2020   *.for >> serch.out
grep 1999   *.seq >> serch.out
grep 2000   *.seq >> serch.out
grep 2001   *.seq >> serch.out
grep 2010   *.seq >> serch.out
grep 2020   *.seq >> serch.out
